from flask import Flask, request, jsonify, render_template
import google.generativeai as genai
import os

app = Flask(__name__)

# Read the Gemini API key from file
API_KEY_FILE = 'gemini api key.txt'
try:
    with open(API_KEY_FILE, 'r') as file:
        GEMINI_API_KEY = file.read().strip()
    genai.configure(api_key=GEMINI_API_KEY)
except FileNotFoundError:
    print(f"Error: Could not find {API_KEY_FILE}.")
    GEMINI_API_KEY = None
except Exception as e:
    print(f"Error reading API key: {e}")
    GEMINI_API_KEY = None

# Initialize the Gemini model
model = genai.GenerativeModel('gemini-2.5-flash')
chat_instances = {} # Dictionary to store chat sessions by IP or ID if needed, for now we will just use a global or simple stateless one.
# For simplicity and statelessness, we can just send the history from the frontend or just pass the current message.
# The `generate_content` call is stateless if we don't use `start_chat`. We'll just pass the full prompt.


# -------------------------------
# Serve Frontend
# -------------------------------
@app.route("/")
def home():
    return render_template("index.html")

# -------------------------------
# Chat Endpoint
# -------------------------------
@app.route("/chat", methods=["POST"])
def chat():
    if not GEMINI_API_KEY:
         return jsonify({"error": "Gemini API key is missing or invalid on the server."}), 500

    data = request.get_json()
    user_message = data.get("message")
    system_prompt = data.get("system_prompt", "You are a helpful, smart, and friendly AI assistant.")

    if not user_message:
        return jsonify({"error": "Message is required"}), 400

    try:
        # Combine system prompt and user message appropriately for Gemini
        prompt = f"System Instructions: {system_prompt}\n\nUser Message: {user_message}"
        
        response = model.generate_content(prompt)
        
        # Gemini sends back a candidate with content
        if response.text:
             return jsonify({
                "choices": [{
                    "message": {
                        "content": response.text
                    }
                }]
            })
        else:
             return jsonify({"error": "No response text generated by Gemini"}), 500

    except Exception as e:
        print(f"Generation error: {e}")
        return jsonify({"error": str(e)}), 500


if __name__ == "__main__":
    app.run(debug=True)
